name: Glitch Sync

# Glitch Project: https://glitch.com/edit/#!/github-action
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Glitch Project
        uses: kanadgupta/glitch-sync@main
        with:
          auth-token: '${{ secrets.GLITCH_AUTH_TOKEN }}'
          project-id: '${{ secrets.GLITCH_PROJECT_ID }}'
